myNew_portfolio/main/urls.py
from django.urls import path

from .views import home, contact

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('contact', contact, name='contact'),
]

myNew_portfolio/myNew_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]


handler404 = "main.views.handle_404"
handler500 = "main.views.handle_500"


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myNew_portfolio/main/models.py
from django.db import models


class Profile(models.Model):
    full_name = models.CharField(max_length=30, null=True, blank=True)
    picture = models.ImageField(upload_to='profile_pics')
    about_me = models.TextField(max_length=500)
    birthday = models.DateField()
    phone = models.CharField(max_length=17)
    email = models.EmailField()
    address = models.CharField(max_length=100)
    education_degree = models.CharField(max_length=20)
    cv = models.FileField(upload_to='cv', blank=True, null=True)

    def __str__(self):
        return self.full_name


class Skill(models.Model):
    name = models.CharField(max_length=50)
    percentage = models.PositiveBigIntegerField()
    color = models.CharField(max_length=20)
    is_field = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Resume(models.Model):
    title = models.CharField(max_length=100)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    place = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-start_date', )


class Education(Resume):
    pass


class Experience(Resume):
    pass


class Service(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='services')
    description = models.TextField(max_length=500)

    def __str__(self):
        return self.name


class Project(models.Model):
    title = models.CharField(max_length=100)

    class CATEGORIES(models.TextChoices):
        web = 'web',
        mobile = 'mobile',
        desktop = 'desktop',
        upcoming = 'upcoming'
    category = models.CharField(
        max_length=20,
        choices=CATEGORIES.choices,
        default='Web apps'
    )
    description = models.TextField(max_length=500)
    image_one = models.ImageField(upload_to='projects')
    image_two = models.ImageField(
        upload_to='projects', blank=True, null=True)
    image_three = models.ImageField(
        upload_to='projects', blank=True, null=True)
    image_four = models.ImageField(
        upload_to='projects', blank=True, null=True)
    image_five = models.ImageField(
        upload_to='projects', blank=True, null=True)
    image_six = models.ImageField(
        upload_to='projects', blank=True, null=True)
    image_seven = models.ImageField(
        upload_to='projects', blank=True, null=True)
    image_eight = models.ImageField(
        upload_to='projects', blank=True, null=True)
    image_nine = models.ImageField(
        upload_to='projects', blank=True, null=True)
    image_ten = models.ImageField(
        upload_to='projects', blank=True, null=True)
    image_eleven = models.ImageField(
        upload_to='projects', blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-id', )


class Social (models.Model):
    my_facebook = models.URLField()
    my_twitter = models.URLField()
    my_linkedin = models.URLField()

    def __str__(self):
        return 'Social Media'

myNew_portfolio/main/forms.py
from django import forms


class ContactMe(forms.Form):
    class Meta:
        name = forms.CharField(max_length=50)
        email = forms.EmailField()
        subject = forms.CharField(max_length=200)
        message = forms.CharField(widget=forms.Textarea)

myNew_portfolio/main/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.core.mail import send_mail
from django.core.mail import BadHeaderError

from .models import Profile, Skill, Education, Experience, Service, Project, Social
from .forms import ContactMe


def home(request):
    profile = Profile.objects.first()
    skills = Skill.objects.all()
    educations = Education.objects.all()
    experiences = Experience.objects.all()
    services = Service.objects.all()
    projects = Project.objects.all()
    social = Social.objects.first()
    form = ContactMe(request.POST or None)

    context = {
        'profile': profile,
        'skills': skills,
        'educations': educations,
        'experiences': experiences,
        'services': services,
        'projects': projects,
        'social': social,
        'form': form
    }

    return render(request, 'main/home.html', context)


def contact(request):
    if request.is_ajax():
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        if name and email and subject and message:
            try:
                send_mail(subject, message, email,
                          ['f.benayad95@gmail.com'])
            except BadHeaderError:
                return JsonResponse({
                    'msg': 'Invalid header found.',
                    'type': 'error',
                    'confirmation': 'true',
                })
            return JsonResponse({
                'msg': 'Your email has been sent successfully to Fouad',
                'type': 'success',
                'confirmation': 'true'
            })
        else:
            return JsonResponse({
                'msg': 'Make sure all fields are entered are valid.',
                'type': 'error',
                'confirmation': 'true'
            })


def handle_404(request, exception):
    data = {
        'status_code': "404",
        'error_message': "The link you followed may be broken, or the page may have been removed."
    }
    return render(request, 'error_handler.html', data)


def handle_500(request):
    data = {
        'status_code': "500",
        'error_message': "Server Error, Something went wrong."
    }
    return render(request, 'error_handler.html', data)

myNew_portfolio/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.ico' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <!-- Custom Js -->
    <script src="{% static 'functions.js' %}" defer></script>

    {% block scripts %}
    {% endblock scripts %}

    <title>Fouad Benayad - {% block title %}{% endblock title %}</title>
</head>

<body>

    <!-- ======= Mobile nav toggle button ======= -->
    <!-- <button type="button" class="mobile-nav-toggle d-xl-none"><i class="bi bi-list mobile-nav-toggle"></i></button> -->
    <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>
    <!-- ======= Header ======= -->
    <header id="header" class="d-flex flex-column justify-content-center">

        <nav id="navbar" class="navbar nav-menu">
            <ul>
                <li><a href="#hero" class="nav-link scrollto active"><i class="bx bx-home"></i> <span>Home</span></a>
                </li>
                <li><a href="#about" class="nav-link scrollto"><i class="bx bx-user"></i> <span>About</span></a></li>
                <li><a href="#resume" class="nav-link scrollto"><i class="bx bx-file-blank"></i> <span>Resume</span></a>
                </li>
                <li><a href="#services" class="nav-link scrollto"><i class="bx bx-server"></i> <span>Services</span></a>
                <li><a href="#portfolio" class="nav-link scrollto"><i class="bx bx-book-content"></i>
                        <span>Portfolio</span></a></li>
                </li>
                <li><a href="#contact" class="nav-link scrollto"><i class="bx bx-envelope"></i> <span>Contact</span></a>
                </li>
            </ul>
        </nav><!-- .nav-menu -->

    </header><!-- End Header -->

    {% block content %}

    {% endblock content %}
    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="container">
            <h3>Fouad Benayad</h3>
            <p>Software Developer & Cyber Security Engineer.</p>
            {% if social %}
            <div class="social-links">
                <a href="{{ social.my_linkedin }}" class="linkedin" target="_blank"><i class="bx bxl-linkedin"></i></a>
                <a href="{{ social.my_facebook }}" class="facebook" target="_blank"><i class="bx bxl-facebook"></i></a>
                <a href="{{ social.my_twitter }}" class="twitter" target="_blank"><i class="bx bxl-twitter"></i></a>
            </div>
            {% endif %}
            <div id="copyright-el" class="copyright"></div>
            <div class="credits">
                Developped by <a href="">Fouad Benayad</a>
                <div class="mt-2">Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a
                        href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
            </div>
        </div>
    </footer><!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous">
        </script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/typed.js/typed.min.js' %}"></script>
    <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
    <script src="{% static 'assets/vendor/epc/jquery.easypiechart.min.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

myNew_portfolio/templates/error_handler.html
<div id="notfound">
    <div class="notfound">
        <div>
            <div class="notfound-404">
                <h1>!</h1>
            </div>
            <h2>Error<br>{{ status_code }}</h2>
        </div>
        <p>{{ error_message }}<a href="{% url 'main:home' %}">Back to homepage</a></p>
    </div>
</div>